-- ============================================================
-- Migration: 00000000000027_referee_pool
-- Purpose:
--   1. Create referee_volunteers table for player volunteer tracking
--   2. Create referee_assignments table for audit/history
--   3. Create available_referees view for match assignment
-- ============================================================

BEGIN;

-- 1. CREATE referee_volunteers TABLE
CREATE TABLE IF NOT EXISTS referee_volunteers (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tournament_id UUID REFERENCES tournaments(id) ON DELETE CASCADE,
    person_id UUID REFERENCES persons(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    is_active BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(tournament_id, person_id)
);

COMMENT ON TABLE referee_volunteers IS 'Tracks which players have volunteered to be referees';
COMMENT ON COLUMN referee_volunteers.is_active IS 'True if player is currently available to referee';

-- 2. CREATE referee_assignments TABLE
CREATE TABLE IF NOT EXISTS referee_assignments (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    match_id UUID REFERENCES matches(id) ON DELETE CASCADE,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    assigned_by UUID REFERENCES auth.users(id) ON DELETE SET NULL,
    is_suggested BOOLEAN DEFAULT FALSE,
    is_confirmed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(match_id)
);

COMMENT ON TABLE referee_assignments IS 'Audit trail of referee assignments to matches';
COMMENT ON COLUMN referee_assignments.is_suggested IS 'True if this was auto-generated by the system';
COMMENT ON COLUMN referee_assignments.is_confirmed IS 'True if organizer has confirmed this assignment';

-- 3. CREATE available_referees VIEW
-- Returns users who are checked-in, have a user_id, and are NOT playing in the match
CREATE OR REPLACE VIEW available_referees AS
WITH match_players AS (
    -- Get all player user_ids for each match
    SELECT 
        m.id AS match_id,
        ARRAY_AGG(DISTINCT p.user_id) FILTER (WHERE p.user_id IS NOT NULL) AS playing_user_ids
    FROM matches m
    JOIN categories c ON c.id = m.category_id
    JOIN tournament_entries te ON te.category_id = c.id
    JOIN entry_members em ON em.entry_id = te.id
    JOIN persons p ON p.id = em.person_id
    WHERE te.checked_in_at IS NOT NULL
    GROUP BY m.id
)
SELECT DISTINCT ON (mp.match_id, rv.user_id)
    mp.match_id,
    p.user_id,
    p.id AS person_id,
    t.id AS tournament_id,
    t.name AS tournament_name,
    c.name AS category_name,
    m.round_name,
    -- Count how many confirmed matches this user has refereed
    COALESCE(
        (SELECT COUNT(*) 
         FROM referee_assignments ra2 
         WHERE ra2.user_id = p.user_id AND ra2.is_confirmed = TRUE),
        0
    ) AS matches_refereed
FROM match_players mp
CROSS JOIN LATERAL unnest(mp.playing_user_ids) WITH ORDINALITY AS pp(user_id, ord)
JOIN matches m ON m.id = mp.match_id
JOIN categories c ON c.id = m.category_id
JOIN tournaments t ON t.id = c.tournament_id
JOIN persons p ON p.user_id = pp.user_id
JOIN tournament_entries te ON te.category_id = c.id 
    AND te.checked_in_at IS NOT NULL
    AND EXISTS (
        SELECT 1 FROM entry_members em2 
        WHERE em2.entry_id = te.id AND em2.person_id = p.id
    )
JOIN referee_volunteers rv ON rv.person_id = p.id 
    AND rv.tournament_id = t.id 
    AND rv.is_active = TRUE
WHERE p.user_id != ALL(COALESCE(mp.playing_user_ids, ARRAY[]::UUID[]))
  AND NOT EXISTS (
      SELECT 1 FROM referee_assignments ra
      WHERE ra.match_id = mp.match_id AND ra.is_confirmed = TRUE
  )
ORDER BY mp.match_id, rv.user_id, matches_refereed ASC;

COMMENT ON VIEW available_referees IS 
'Players available to referee a specific match. Excludes: (1) non-checked-in, (2) no user_id, (3) playing in match, (4) already assigned to another match';

-- 4. ADD INDEXES for performance
CREATE INDEX IF NOT EXISTS idx_referee_volunteers_tournament 
ON referee_volunteers(tournament_id, is_active);

CREATE INDEX IF NOT EXISTS idx_referee_volunteers_person 
ON referee_volunteers(person_id);

CREATE INDEX IF NOT EXISTS idx_referee_assignments_match 
ON referee_assignments(match_id, is_confirmed);

CREATE INDEX IF NOT EXISTS idx_referee_assignments_user 
ON referee_assignments(user_id);

CREATE INDEX IF NOT EXISTS idx_available_referees_match 
ON available_referees(match_id);

CREATE INDEX IF NOT EXISTS idx_available_referees_user 
ON available_referees(user_id);

-- 5. ADD matches_refereed counter to athlete_stats (for round-robin balancing)
ALTER TABLE athlete_stats 
ADD COLUMN IF NOT EXISTS matches_refereed INTEGER DEFAULT 0;

COMMENT ON COLUMN athlete_stats.matches_refereed IS 
'Total matches refereed by this player (for round-robin balancing)';

-- 6. FUNCTION to update matches_refereed when assignment is confirmed
CREATE OR REPLACE FUNCTION update_referee_stats()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.is_confirmed = TRUE AND OLD.is_confirmed = FALSE THEN
        -- Increment matches_refereed for the referee
        UPDATE athlete_stats
        SET matches_refereed = matches_refereed + 1
        WHERE person_id = (
            SELECT id FROM persons WHERE user_id = NEW.user_id
        );
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_referee_stats ON referee_assignments;
CREATE TRIGGER trg_update_referee_stats
AFTER UPDATE ON referee_assignments
FOR EACH ROW
EXECUTE FUNCTION update_referee_stats();

COMMIT;
